### ISSUE TITLE
Dev Tasks - Client Side

### ISSUE THREAD

**Issue by GVill683** [marvelousdesign/GMH-ShortURL#19]
Hi Team,
I will be in charge of completing the following issues. 

2. Styling

Improve the styling of the page, using Flexbox and CSS grid for layout. DO NOT use a CSS framework like Bootstrap. Extra credit if your site is mobile responsive, and extra-extra credit if it's designed mobile-first.

3. Documentation

Refine your README.md to include updated instructions. I

**Comment by ayyrickay** [comment]
@GVill683 Good work - but now can you make this two different issues? Think of issues like a to-do list. You should have one issue named something like `Improve client side styling` and another called `Update README.md with new instructions`. Just something that indicates what needs to be done

**Comment by ayyrickay** [comment]
Also, you assigned Sarah and I, but if you're going to complete the task, assign it to yourself!

**Comment by GVill683** [comment]
Done!
