### ISSUE TITLE
Improve client side styling

### ISSUE THREAD

**Issue by GVill683** [marvelousdesign/GMH-ShortURL#20]

**Comment by marvelousdesign** [comment]
For the mobile response layout, it could use some tweaking. Like scaling down the font sizes and extending the width of the .input-style, you can also add some margin between the two too.

**Comment by marvelousdesign** [comment]
for #output a { ... } can you change them to this, so it apply to all links, feel free to do styles for a:hover, a:active.
```
a,
a:visited {
    color: #d34;
    text-decoration: none;
}
```
Also we can get rid of .output-styles, etc. since it's not being used.

**Comment by GVill683** [comment]
Hi Mary,
Ill take a look and apply the new changes later in the week.
Should take no time at all.
Gabriel
