### ISSUE TITLE
Update README.md with new instructions

### ISSUE THREAD

**Issue by GVill683** [marvelousdesign/GMH-ShortURL#21]

**Comment by marvelousdesign** [comment]
I've edited it some in the latest pull #22

**Comment by ayyrickay** [comment]
@GVill683 @marvelousdesign Check out [this template](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) for some ideas on how to update your README.md

**Comment by marvelousdesign** [comment]
***Testing markup style***

# GMH-ShortURL

This application takes long URLs and shortens them. It was built from scratch with Javascript.

Team members included Gabriel, Mary, Hannah, and Alexandra


# Getting Started

These instructions will get you a copy of the project up and running on your local machine for development and testing purposes. See deployment for notes on how to deploy the project on a live system.

# Prerequisites

Run git clone to clone this repo
```
git clone https://github.com/marvelousdesign/GMH-ShortURL.git
```

Ensure that node modules are installed in your new project folder. Use ‘npm ci’ it will remove existing node_modules/ if they exists, then installs the exact versions.

```
npm ci
```
You should have body-parser, cors, dotenv, errorhandler, express, mongodb, mongoose, morgan, path, request, and its dependencies.

# Running the node server

If you are in the root of the git repo: To start app, type in your terminal 'node server/app.js' and the app will show that it’s listening on port 3000 in your terminal.
```
node server/app.js
```

Go to localhost:3000 in your browser, and it will display the client/index.html.
```
http://localhost:3000/
```

# Deployment

If deploying to Heroku, register for a Heroku account and go through their tutorial up to Provision add-ons.

- Create a new app on dashboard.heroku.com/apps, then name your app (optional).
- Connect it to your existing git via Heroku CLI (set that up if you haven't already).

```
heroku git:remote -a randomnonsense
```

- Connect the app with Github, and you can setup automatic deploy or deploy manually on: dashboard.heroku.com/apps/randomnonsense/deploy/github
- Best to manually deploy after Master has been merge with your working branch. So you don't have to deal with heroku being ahead of your master branch on github, and uncommitting then committing changes.
- You can see the tail of the logs by using 'heroku logs --tail' in your terminal

```
heroku logs --tail
```

Register for a mlab account, create a new MongoDB Deployment and make a user for the database. So you don't have to tie your Credit Card to your Heroku acc. They will give you a link like so and you can put it into your .env.
```
MONGOLAB_URI='mongodb://dbuser:dbpassword@ab112345.mlab.com:12345/database'
```
To add it to Heroku via terminal, you can use 'heroku config:set'
```
heroku config:set MONGOLAB_URI='mongodb://dbuser:dbpassword@ab112345.mlab.com:12345/database'
```

After you deploy it to heroku, you can use 'heroku open' on your terminal to open the webpage on your browser.
```
heroku open
```
Simlarly you can use 'heroku local' it will fire up node with the web.1 dyno process, then go to localhost:5000 on your browser. You'll see the last state of when you deploy it to heroku.
```
heroku local
```
