### ISSUE TITLE
Deploy to heroku

### ISSUE THREAD

**Issue by marvelousdesign** [marvelousdesign/GMH-ShortURL#25]
Provisioning files for heroku
Adding Procfile with ```web: node server/app.js```
Replacing all instance of http://localhost:3000/ with https://gmshortener.herokuapp.com/
Updating project with any necessary changes
Connecting mlab and heroku with (for example)
```
heroku config:set MONGOLAB_URI='mongodb://<user>:<password>@example11234.mlab.com:1234/database'
```

**Comment by marvelousdesign** [comment]
It's done see #22

**Comment by marvelousdesign** [comment]
Heroku steps to add to the readme:

- Create a new app on https://dashboard.heroku.com/apps, then name your app (optional).
- Connect it to your existing git via Heroku CLI (set that up if you haven't already)
    ```heroku git:remote -a randomnonsense```
- Connect the app with Github, and you can setup automatic deploy or deploy manually on: https://dashboard.heroku.com/apps/randomnonsense/deploy/github
- Best to manually deploy after Master has been merge with your working branch. So you don't have to deal with heroku being ahead of your master branch on github, and uncommitting then committing changes.

**Comment by ayyrickay** [comment]
@marvelousdesign Could you also add an `example.env` file? It's unclear where the .env goes, currently.

**Comment by vanwars** [comment]
Good point. For the client side, there are a number of strategies ppl can use to have different settings for different boxes, but for you, something like this could work for createPost.js and getPosts.js:

```js
let urlBase = 'http://localhost:3000'
if (window.location.indexOf('gmshortener.herokuapp.com') !== -1) {
   urlBase = 'https://gmshortener.herokuapp.com/'
}
```

**Comment by marvelousdesign** [comment]
Thanks Sarah! Oh I didn't see your edits via email, but this works: (without toString() it throws a TypeError. I guess consts is better for non mutability.

```
let urlBase = 'http://localhost:3000'
if (window.location.toString().indexOf('gmshortener.herokuapp.com') !== -1) {
    urlBase = 'https://gmshortener.herokuapp.com/'
}
```
But the shorten url output will depend on the process.env.BASE_URI vs process.env.LOCALHOST we set manually. Is there an similar function to this? Probably not window.location, but can it be dynamically changed?

**Comment by ayyrickay** [comment]
In the spirit of decoupling client and server, I think this shows that you should be returning a full URL to the client. Couldn't you return the process.env.BASE_URI in the response, and let the client decide how to put it all together?

**Comment by marvelousdesign** [comment]
Ok, it's in the latests commit! #31 dab7b9a
