### ISSUE TITLE
(Rewrite server response to include shortened URL)---Gabriel

### ISSUE THREAD

**Issue by GVill683** [marvelousdesign/GMH-ShortURL#7]
Figure it out!

**Comment by GVill683** [comment]
Hi Mary,
No worries, I will look over this and get back to you with the new changes.
Sincerely,
Gabriel

**Comment by GVill683** [comment]
Hi Mary,
All id's have been switched to classless for the styles. I have kept the
id's strictly to the javascript as well.

To get the values for the "user.url-input". First make sure you have a copy
of node modules  within the GMH-ShortURL folder on your local machine.
Then cd into the server folder and type "node app.js" to start to the
server.

Open the index.html on google chrome. Insert a longUrL and hit the shorten
button.
Inspect the generator on the google within the console.

 You should get this.

Hope this helps!
Gabriel

**Comment by marvelousdesign** [comment]
I'm up to date and running "node server/app.js" in the /GMH-ShortURL/ folder.

I'm getting errors in the browser & terminal if the id are as is "url-input" when using this bit of code in app.js app.post
```
var user = req.body
    console.log('req.body: ' + JSON.stringify(user))
    console.log(user.url-input)
```
Javascript doesn't like "url-input" as a variable, but as a string it's ok like so.
```
console.log(req.body['url-input'])
or console.log(user['url-input'])
```
It's a way to get around the dash issue and I can use this workaround.
ref: https://stackoverflow.com/questions/2119629/javascript-and-css-using-dashes

**Comment by GVill683** [comment]
Do you have time in the day for a video chat for us to go over the code?

**Comment by marvelousdesign** [comment]
I'm free now if you want or anytime later.

**Comment by GVill683** [comment]
I can do it now.
What platform show we use?

**Comment by marvelousdesign** [comment]
Lets move to the convo to gmail, since replying to issues is public facing.
For Zoom one of us needs to register as a host if they haven't already.
I'm also ok with google hangouts, and screen sharing.

**Comment by GVill683** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>URL Shortener</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="css/main.css">
</head>
<body>
<main>
<h1>Enter a url to shorten:</h1>

<label for="urlinput">LongURL:</label>
<input type="text" id="urlinput" class="inputstyles" value="http://"
placeholder="http://">

<button id="shortenbutton" class="shorten-button-styles">Shorten!</button>

<label for="urloutput">ShortURL:</label>
<output type="text" id="urloutput" class="outputstyles" ></output>
</main>
<script src="js/post.js"></script>
</body>
</html>

**Comment by GVill683** [comment]
body {
background-color: #013;
}

main {
display: flex;
flex-direction: column;
justify-content: center;
align-items: center;
color: white;
font-family: Arial, Helvetica, sans-serif;
font-size: 18px;
margin: 5em;
}

.input-styles {
font: inherit;
font-size: 3rem;
font-family: monospace;
font-weight: bold;
padding: 0.3em;
width: 80%;
background-color: rgba(255, 255, 255, 0.5);
border: 0;
outline: 0;
}

.input-stylest:focus {
background-color: rgba(255, 255, 255, 0.8);
}

.shorten-button-styles{
background-color: #d34;
padding: 1rem 2rem;
color: white;
font-family: Arial, Helvetica, sans-serif;
font-size: 1.5rem;
border: 0;
margin: 3rem;
cursor: pointer;
}

.output-styles{
font: inherit;
font-size: 3rem;
font-family: monospace;
font-weight: bold;
padding: 0.3em;
padding-bottom: 1.3em;
width: 80%;
background-color: rgba(255, 255, 255, 0.5);
border: 0;
outline: 0;
}

.output-styles:focus {
background-color: rgba(255, 255, 255, 0.8);
}

/* #out a {
color: #d34;
} */



On Sat, Apr 28, 2018 at 3:46 PM, Gabriel Pandolfo <pandolfogabriel@gmail.com
> wrote:

> <!DOCTYPE html>
> <html lang="en">
> <head>
> <meta charset="utf-8">
> <title>URL Shortener</title>
> <meta name="viewport" content="width=device-width,initial-scale=1">
> <link rel="stylesheet" href="css/main.css">
> </head>
> <body>
> <main>
> <h1>Enter a url to shorten:</h1>
>
> <label for="urlinput">LongURL:</label>
> <input type="text" id="urlinput" class="inputstyles" value="http://"
> placeholder="http://">
>
> <button id="shortenbutton" class="shorten-button-styles">Shorten!</button>
>
> <label for="urloutput">ShortURL:</label>
> <output type="text" id="urloutput" class="outputstyles" ></output>
> </main>
> <script src="js/post.js"></script>
> </body>
> </html>
>
>
>

**Comment by ayyrickay** [comment]
Great correspondence here. Quick note that when you're sending code snippets, you can use markdown to set things up as code. For example:

`
console.log('Hello, world!')
`

I did this by using backticks (```) around the text I want to look like code. You can also just click the <> icon
